In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("thyroidDF.csv")

In [8]:
df.head()

age sex on_thyroxine query_on_thyroxine on_antithyroid_meds sick pregnant  \
0   29   F            f                  f                   f    f        f   
1   29   F            f                  f                   f    f        f   
2   41   F            f                  f                   f    f        f   
3   36   F            f                  f                   f    f        f   
4   32   F            f                  f                   f    f        f   

  thyroid_surgery I131_treatment query_hypothyroid  ...    TT4 T4U_measured  \
0               f              f                 t  ...    NaN            f   
1               f              f                 f  ...  128.0            f   
2               f              f                 f  ...    NaN            f   
3               f              f                 f  ...    NaN            f   
4               f              f                 f  ...    NaN            f   

  T4U FTI_measured FTI TBG_measured   TBG  referral_source target  patient_id  
0 NaN            f NaN            f   NaN            other      -   840801013  
1 NaN            f NaN            f   NaN            other      -   840801014  
2 NaN            f NaN            t  11.0            other      -   840801042  
3 NaN            f NaN            t  26.0            other      -   840803046  
4 NaN            f NaN            t  36.0            other      S   840803047  

[5 rows x 31 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9172 entries, 0 to 9171
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  9172 non-null   int64  
 1   sex                  8865 non-null   object 
 2   on_thyroxine         9172 non-null   object 
 3   query_on_thyroxine   9172 non-null   object 
 4   on_antithyroid_meds  9172 non-null   object 
 5   sick                 9172 non-null   object 
 6   pregnant             9172 non-null   object 
 7   thyroid_surgery      9172 non-null   object 
 8   I131_treatment       9172 non-null   object 
 9   query_hypothyroid    9172 non-null   object 
 10  query_hyperthyroid   9172 non-null   object 
 11  lithium              9172 non-null   object 
 12  goitre               9172 non-null   object 
 13  tumor                9172 non-null   object 
 14  hypopituitary        9172 non-null   object 
 15  psych                9172 non-null   o

In [10]:
df.describe()

age          TSH           T3          TT4          T4U  \
count   9172.000000  8330.000000  6568.000000  8730.000000  8363.000000   
mean      73.555822     5.218403     1.970629   108.700305     0.976056   
std     1183.976718    24.184006     0.887579    37.522670     0.200360   
min        1.000000     0.005000     0.050000     2.000000     0.170000   
25%       37.000000     0.460000     1.500000    87.000000     0.860000   
50%       55.000000     1.400000     1.900000   104.000000     0.960000   
75%       68.000000     2.700000     2.300000   126.000000     1.065000   
max    65526.000000   530.000000    18.000000   600.000000     2.330000   

               FTI         TBG    patient_id  
count  8370.000000  349.000000  9.172000e+03  
mean    113.640746   29.870057  8.529473e+08  
std      41.551650   21.080504  7.581969e+06  
min       1.400000    0.100000  8.408010e+08  
25%      93.000000   21.000000  8.504090e+08  
50%     109.000000   26.000000  8.510040e+08  
75%     128.000000   31.000000  8.607110e+08  
max     881.000000  200.000000  8.701190e+08

In [11]:
features=df[['age', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH',
        'T3','TT4', 'T4U',
        'FTI',  'TBG']]
features

age lithium goitre tumor hypopituitary psych  TSH   T3    TT4   T4U  \
0      29       f      f     f             f     f  0.3  NaN    NaN   NaN   
1      29       f      f     f             f     f  1.6  1.9  128.0   NaN   
2      41       f      f     f             f     f  NaN  NaN    NaN   NaN   
3      36       f      f     f             f     f  NaN  NaN    NaN   NaN   
4      32       f      f     f             f     f  NaN  NaN    NaN   NaN   
...   ...     ...    ...   ...           ...   ...  ...  ...    ...   ...   
9167   56       f      f     f             f     f  NaN  NaN   64.0  0.83   
9168   22       f      f     f             f     f  NaN  NaN   91.0  0.92   
9169   69       f      f     f             f     f  NaN  NaN  113.0  1.27   
9170   47       f      f     f             f     f  NaN  NaN   75.0  0.85   
9171   31       f      f     f             f     f  NaN  NaN   66.0  1.02   

       FTI   TBG  
0      NaN   NaN  
1      NaN   NaN  
2      NaN  11.0  
3      NaN  26.0  
4      NaN  36.0  
...    ...   ...  
9167  77.0   NaN  
9168  99.0   NaN  
9169  89.0   NaN  
9170  88.0   NaN  
9171  65.0   NaN  

[9172 rows x 12 columns]

In [12]:
cols=['lithium','goitre', 'tumor', 'hypopituitary', 'psych']
encoded={'f':0,"t":1}
for col in cols: 
    features[col]=[encoded[i] for i in features[col].values]

<ipython-input-12-947d1b2a82d1>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features[col]=[encoded[i] for i in features[col].values]


In [13]:
features

age  lithium  goitre  tumor  hypopituitary  psych  TSH   T3    TT4  \
0      29        0       0      0              0      0  0.3  NaN    NaN   
1      29        0       0      0              0      0  1.6  1.9  128.0   
2      41        0       0      0              0      0  NaN  NaN    NaN   
3      36        0       0      0              0      0  NaN  NaN    NaN   
4      32        0       0      0              0      0  NaN  NaN    NaN   
...   ...      ...     ...    ...            ...    ...  ...  ...    ...   
9167   56        0       0      0              0      0  NaN  NaN   64.0   
9168   22        0       0      0              0      0  NaN  NaN   91.0   
9169   69        0       0      0              0      0  NaN  NaN  113.0   
9170   47        0       0      0              0      0  NaN  NaN   75.0   
9171   31        0       0      0              0      0  NaN  NaN   66.0   

       T4U   FTI   TBG  
0      NaN   NaN   NaN  
1      NaN   NaN   NaN  
2      NaN   NaN  11.0  
3      NaN   NaN  26.0  
4      NaN   NaN  36.0  
...    ...   ...   ...  
9167  0.83  77.0   NaN  
9168  0.92  99.0   NaN  
9169  1.27  89.0   NaN  
9170  0.85  88.0   NaN  
9171  1.02  65.0   NaN  

[9172 rows x 12 columns]

In [14]:
name0=df['target'].unique().tolist()
name=sorted(name0)
print(name)
N=list(range(len(name)))
normal_mapping=dict(zip(name,N)) 
reverse_mapping=dict(zip(N,name))
df['target']=df['target'].map(normal_mapping)

['-', 'A', 'AK', 'B', 'C', 'C|I', 'D', 'D|R', 'E', 'F', 'FK', 'G', 'GI', 'GK', 'GKJ', 'H|K', 'I', 'J', 'K', 'KJ', 'L', 'LJ', 'M', 'MI', 'MK', 'N', 'O', 'OI', 'P', 'Q', 'R', 'S']


In [15]:
target_encoded={j:i for i,j in enumerate(df['target'].unique())}
target=[target_encoded[i] for i in df['target'].values]
target=np.array(target).reshape(-1,1)
target

array([[0],
       [0],
       [0],
       ...,
       [5],
       [0],
       [0]])

In [16]:
target[9149]

array([2])

In [17]:
target[9158]

array([15])

In [18]:
import sklearn as sk
from sklearn.preprocessing import StandardScaler

In [21]:
features= StandardScaler().fit_transform(features)

In [22]:
features

array([[-0.0376344 , -0.10120978, -0.0961403 , ...,         nan,
                nan,         nan],
       [-0.0376344 , -0.10120978, -0.0961403 , ...,         nan,
                nan,         nan],
       [-0.02749851, -0.10120978, -0.0961403 , ...,         nan,
                nan, -0.89642781],
       ...,
       [-0.00384811, -0.10120978, -0.0961403 , ...,  1.46716514,
        -0.59305028,         nan],
       [-0.02243057, -0.10120978, -0.0961403 , ..., -0.62918238,
        -0.61711816,         nan],
       [-0.03594508, -0.10120978, -0.0961403 , ...,  0.21933924,
        -1.17067919,         nan]])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(features,target,test_size=0.2)

In [26]:
x_train

array([[-8.91605163e-03, -1.01209777e-01, -9.61403024e-02, ...,
                    nan,             nan, -4.68880075e-01],
       [-4.69479138e-04, -1.01209777e-01, -9.61403024e-02, ...,
         1.11777388e+00, -1.11692864e-01,             nan],
       [-2.58091966e-02, -1.01209777e-01, -9.61403024e-02, ...,
        -4.79443270e-01, -1.45949364e+00,             nan],
       ...,
       [-3.51004264e-02, -1.01209777e-01, -9.61403024e-02, ...,
         3.56351265e+00, -5.44914542e-01,             nan],
       [-3.00324829e-02, -1.01209777e-01, -9.61403024e-02, ...,
         3.19165307e-01, -6.17118155e-01,             nan],
       [-4.18576844e-02, -1.01209777e-01, -9.61403024e-02, ...,
        -6.29182378e-01, -1.35760735e-01,             nan]])

In [29]:
len(x_train)


7337

In [30]:
len(x_test)

1835

In [38]:
median = df["TSH"].median()
df["TSH"].fillna(median,inplace=True)

IndexError: ignored

In [ ]:
median = df["TT4"].median()
df["TT4"].fillna(median,inplace=True)

In [36]:
median = df["FTI"].median()
df["FTI"].fillna(median,inplace=True)

In [ ]:
median = df["T3"].median()
df["T3"].fillna(median,inplace=True)

In [ ]:
median = df["T4U"].median()
df["T4U"].fillna(median,inplace=True)

In [39]:
median = df["TBG"].median()
df["TBG"].fillna(median,inplace=True)

In [1]:
median = df['sex'].median()
df['age'].fillna(median, inplace=True)

NameError: ignored

In [40]:
from sklearn.tree import DecisionTreeClassifier
classifer = DecisionTreeClassifier(criterion="entropy", random_state=0)
classifer.fit(x_train,y_train)
y_train= classifer.predict(x_train)

ValueError: ignored